class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        check_dict = {}

        for letter in t:
            check_dict[letter] = check_dict.get(letter, 0) + 1

        for letter in s:
            check_dict[letter] -= 1
            if check_dict[letter] == 0:
                del check_dict[letter]

        for letter in check_dict.keys():
            return letter


"""
389. Find the Difference
Easy
4.1K
437
Companies
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"


Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
"""